### ISSUE TITLE
options.url is being ignored

### ISSUE THREAD

**Issue by azaslonov** [jonkemp/inline-css#74]
Hello and thank you for wonderful library!

It looks like processor ignores "url" option:

Code:
```
        const myhtml = `<style>div{color:red;background-image: url("image.png")}</style><div/><img src="image.png" /><a href="/page-relative">Page</a>`;

        inlineCss(myhtml, { url: "http://abc.com" })
            .then(function (html) {
                console.log(html); 
                debugger;
            });
```
Output:
```
<div style="background-image: url('image.png'); color: red;"><img src="image.png"><a href="/page-relative">Page</a></div>
```

Could you please assist with this?

**Comment by niklas-englert** [comment]
To @jonkemp,  
this issue is still open and exists even with the given example on the [homepage](https://github.com/jonkemp/inline-css#readme) (tested using RunKit):

![https://i.imgur.com/k3Ypk68.png](https://i.imgur.com/k3Ypk68.png)

If there isn't a "fix" to expect, it would be appreciated to remove this feature from the homepage or mark it as "broken" or "deprecated".

**Comment by jonkemp** [comment]
My apologies. It appears the docs are wrong here. I will work on getting it corrected. Thanks.
